services:
  - type: web
    name: parlour-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: parlour-api
          property: port
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false